
/*
This program adds two binary numbers
The bits are summed in pairs.
Each summations may produce a carry
which must be added to the next two bits.

See
https://www.geeksforgeeks.org/digital-logic/binary-adder-with-logic-gates/

for an explanation.

Notice that some of the logic functions we have been looking at are key components
in an adder. We implement them here in software.  When implemented in hardware
they are called logic gates 

Bit_adder truth table

Inputs are A, B and Carry_in: Cin
Outputs are Sum and Carry_out: Cout

Logic adder truth table fot one pair of bits A and B
Cin is the carry generated by the previus pair if bits
Cout is the carry to be passed to the next summation.

A             0 0 0 0 1 1 1 1
B             0 0 1 1 0 0 1 1
Cin           0 1 0 1 0 1 0 1
A^B           0 0 1 1 1 1 0 0
(A^B)^Cin     0 1 1 0 1 0 0 1
Sum           0 1 1 0 1 0 0 1
Cout          0 0 0 1 0 1 1 1

if Cin is zero  Cout is A&B
if Cin is unity Cout is A|B
*/



#include "SW_multiplication_header.h"
#include "Local_subroutines.c"



//Type main rotine here












/*****************************************************************************************************************************************/
